"""expand jobs table for full HR workflow

Revision ID: 447422a89aa7
Revises: c2672c80afcd
Create Date: 2025-08-22 07:04:16.482469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '447422a89aa7'
down_revision: Union[str, None] = 'c2672c80afcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('seniority', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('domain_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('screening_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('ats_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'summary')
    op.drop_column('jobs', 'ats_keywords')
    op.drop_column('jobs', 'screening_questions')
    op.drop_column('jobs', 'domain_tags')
    op.drop_column('jobs', 'seniority')
    # ### end Alembic commands ###
